DELETE http://localhost:3001/userDelete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTk0ZDQ1MzdlNzM0MjczY2IwNWI0NCIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjIwNzU5MTQ2LCJleHAiOjE2MjEzNjM5NDZ9._4ellgqxYwq1LBclaTgrdFVDBcn1-6Y3rXZflqKxuLY
