POST http://localhost:3001/follow
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTY4NDZjZjYzNTI0MGVjMDc2MWYyZSIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjI2Nzk3NzgzLCJleHAiOjE2Mjc0MDI1ODN9._zurRPvp_N9I8OM8yImVyBfSmGEZaCr_Lbvmo921GZo
Content-Type: application/json

{
    "stopFollowing":"faa"
}