POST http://localhost:3001/follow
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2I4Y2U0YTdmZGY1MzJhNDlmMTAxNiIsIm5hbWVVc2VyIjoic2lpIiwiaWF0IjoxNjMxMjkyOTE2LCJleHAiOjE2MzE4OTc3MTZ9.lzydZb3la_JxsFM8I_rfe8Jpf775qfQmZIOT_QZkPJ8
Content-Type: application/json

{
    "newFollower":"bruno_dev"
}   