GET http://localhost:3001/getPost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODIxOTkxNTQwZTA2MTY4NDNiZjIzMyIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjE5MTk4NjEwLCJleHAiOjE2MTk4MDM0MTB9.TZVe1OIhGGb2AY-3-1_lIqmyJVQNTYueY133kKK4VYQ