POST http://localhost:5000/myStories
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTY4NDZjZjYzNTI0MGVjMDc2MWYyZSIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjI5MTQyNTg0LCJleHAiOjE2Mjk3NDczODR9.mTc4xYYp4Whn9cLOCSN9GqAshrfzpXQ5eewMvyCiYYc
Content-Type: application/json

{
    "img":"apokfpofpij" 
}

# {
#     "idHistorie":"60ff2066b0a5211ae0692541",
#     "deleteHistorie":false
# }