POST http://localhost:3001/myStories
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTY4NDZjZjYzNTI0MGVjMDc2MWYyZSIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjMxMTMwODY5LCJleHAiOjE2MzE3MzU2Njl9.o65PVKxRIj8HGJKvk9hi-6igBkmfDPkxfrFG4D7sSYQ
Content-Type: application/json

{
    "img":"apokfpofpij" 
}

# {
#     "idHistorie":"60ff2066b0a5211ae0692541",
#     "deleteHistorie":false
# }