GET  http://localhost:3001/Profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTY4NDZjZjYzNTI0MGVjMDc2MWYyZSIsIm5hbWVVc2VyIjoiYnJ1bm9fZGV2IiwiaWF0IjoxNjIxNTI1NzE2LCJleHAiOjE2MjIxMzA1MTZ9.8-nXqpEAh3tGndJwZC3CUTLGTkkakJ2vn7eFfEd3ABE
